@SharpNotes.Api_HostAddress = https://localhost:5001/api

GET {{SharpNotes.Api_HostAddress}}/notes/
Accept: application/json

###
GET {{SharpNotes.Api_HostAddress}}/notes/1
Accept: application/json

###
